### ISSUE TITLE
CI is not working

### ISSUE THREAD

**Issue by Comandeer** [ckeditor/ckeditor4-react#22]
Every build on CI fails due to error in Browserstack integration: https://travis-ci.org/ckeditor/ckeditor4-react/jobs/503520465#L487

**Comment by f1ames** [comment]
Now test seems to be failing because of some `before/after each` hooks - https://travis-ci.org/ckeditor/ckeditor4-react/builds/517863257#L502.

**Comment by f1ames** [comment]
Fixed with https://github.com/ckeditor/ckeditor4-react/commit/01695202ce892bf43745451b5a4f95c45f2cd18e.

**Comment by Comandeer** [comment]
Actually this issue was not fixed. For PRs created by external contributors, CI still fails: https://travis-ci.org/ckeditor/ckeditor4-react/builds/534209057

**Comment by f1ames** [comment]
I wonder what might be the issue here... cc @pomek do you have any idea?

**Comment by pomek** [comment]
See https://github.com/ckeditor/ckeditor5-dev/issues/358 and https://github.com/ckeditor/ckeditor5-dev/issues/402.
